name: storipicha_player_workspace
repository: https://github.com/storipicha-org/storipicha_player

packages:
  - packages/*
  - example

scripts:
  analyze:
    exec: flutter analyze .
    description: "Run static analysis across all packages in the workspace."

  format:
    exec: dart format . --set-exit-if-changed
    description: "Check code formatting across all packages."

  test:
    exec: flutter test
    description: "Run unit tests across all packages."

  clean:
    exec: flutter clean
    description: "Clean build directories across all packages."

  create:package:
    run: cd packages && flutter create --template=package
    description: "Create a standard Dart package (Usage: melos run create:package -- <package_name>)"

  create:plugin:
    run: cd packages && flutter create --template=plugin
    description: "Create a platform plugin package (Usage: melos run create:plugin -- --platforms=android <package_name>)"