name: storipicha_player_android
description: "A new Flutter plugin project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.12.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  # 1️⃣ Path to your local interface package
  storipicha_player_platform_interface:
    path: ../storipicha_player_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  plugin:
    platforms:
      android:
        package: io.storipicha.player.android
        pluginClass: StoripichaPlayerAndroidPlugin
        dartPluginClass: StoripichaPlayerAndroid # 👈 Add this line!
